# Generated by Django 4.0.6 on 2022-07-30 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AcercaDeApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Empleado',
        ),
    ]
