# Generated by Django 4.0.6 on 2022-07-23 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cotenido',
            new_name='contenido',
        ),
    ]
