# Generated by Django 4.0.6 on 2022-08-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_comentario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'verbose_name': 'comentario', 'verbose_name_plural': 'comentarios'},
        ),
        migrations.AlterField(
            model_name='comentario',
            name='contenido',
            field=models.TextField(blank=True, null=True),
        ),
    ]
