# Generated by Django 4.0.6 on 2022-08-01 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0003_alter_comentario_options_alter_comentario_contenido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='ientrada',
            new_name='idpost',
        ),
    ]
