# Generated by Django 4.0.6 on 2022-07-26 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0003_alter_post_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subtitulo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
