# Generated by Django 4.0.6 on 2022-08-01 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0004_rename_ientrada_comentario_idpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='idpost',
            new_name='post',
        ),
    ]
