# Generated by Django 4.0.6 on 2022-07-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0006_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comentarios',
            field=models.ManyToManyField(to='BlogApp.comentario'),
        ),
    ]
