# Generated by Django 4.0.6 on 2022-07-27 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0008_remove_post_comentarios'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
