# Generated by Django 4.0.6 on 2022-07-26 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CuentaApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='user',
            new_name='usuario',
        ),
    ]
