# Generated by Django 4.0.6 on 2022-07-31 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CuentaApp', '0003_alter_masdatosusuarios_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masdatosusuarios',
            options={'verbose_name': 'usuario', 'verbose_name_plural': 'usuarios'},
        ),
    ]
