# Generated by Django 4.0.6 on 2022-07-27 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CuentaApp', '0004_rename_user_masdatosusuarios_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masdatosusuarios',
            old_name='usuario',
            new_name='username',
        ),
    ]
