# Generated by Django 4.0.6 on 2022-07-31 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CuentaApp', '0004_alter_masdatosusuarios_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='masdatosusuarios',
            name='first_name',
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
        migrations.AddField(
            model_name='masdatosusuarios',
            name='last_name',
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
    ]
