# Generated by Django 4.0.6 on 2022-07-27 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CuentaApp', '0005_rename_usuario_masdatosusuarios_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masdatosusuarios',
            old_name='username',
            new_name='user',
        ),
    ]
