# Generated by Django 4.0.6 on 2022-07-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CuentaApp', '0007_masdatosusuarios_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masdatosusuarios',
            name='descripcion',
            field=models.CharField(max_length=280),
        ),
    ]
