# Generated by Django 4.0.6 on 2022-07-28 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CuentaApp', '0008_alter_masdatosusuarios_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masdatosusuarios',
            name='descripcion',
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
    ]
