# Generated by Django 4.0.6 on 2022-08-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_masdatosusuarios_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masdatosusuarios',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
        migrations.AlterField(
            model_name='masdatosusuarios',
            name='descripcion',
            field=models.CharField(blank=True, default='No hay descripción', max_length=280, null=True),
        ),
    ]
