# Generated by Django 4.0.6 on 2022-07-31 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_masdatosusuarios_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masdatosusuarios',
            old_name='first_name',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='masdatosusuarios',
            old_name='last_name',
            new_name='nombre',
        ),
    ]
