# Generated by Django 4.0.6 on 2022-07-31 05:11

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_first_name_masdatosusuarios_apellido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masdatosusuarios',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='masdatosusuarios',
            name='nombre',
        ),
        migrations.AddField(
            model_name='masdatosusuarios',
            name='first_name',
            field=models.CharField(blank=True, max_length=280, null=True, verbose_name=django.contrib.auth.models.User),
        ),
        migrations.AddField(
            model_name='masdatosusuarios',
            name='last_name',
            field=models.CharField(blank=True, max_length=280, null=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
